<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- BASE (sub-productos para patrones) -->
<link href="${staticsUrl}/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="${staticsUrl}/rup/custom-theme/jquery-ui-1.8.23.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="${staticsUrl}/rup/basic-theme/theme.rup.sprite-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.base-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.accordion-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.autocomplete-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.breadCrumb-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.combo-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.contextMenu-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.date-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.feedback-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid.jerarquia-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.lang-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.maint-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.menu-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.messages-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.report-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.table-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tabs-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.time-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.toolbar-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tooltip-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.upload-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.validate-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.wizard-2.4.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tree-2.4.1.css" rel="stylesheet" type="text/css" />