<%--  
 -- Copyright 2015 E.J.I.E., S.A.
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 -- 
 -- http://ec.europa.eu/idabc/eupl.html
 -- 
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia. 
 --%>
 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- BASE (sub-productos para patrones) -->
<link href="${staticsUrl}/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="${staticsUrl}/rup/custom-theme/jquery-ui-1.8.23.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="${staticsUrl}/rup/basic-theme/theme.rup.sprite-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.base-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.button-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.accordion-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.autocomplete-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.breadCrumb-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.combo-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.contextMenu-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.date-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.feedback-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid.jerarquia-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.lang-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.maint-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.menu-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.messages-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.report-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tabs-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.time-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.toolbar-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tooltip-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.upload-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.validate-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.wizard-2.4.5.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tree-2.4.5.css" rel="stylesheet" type="text/css" />