 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<link href="${staticsUrl}/rup/css/externals/bootstrap/bt4.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/externals/font-awesome/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/rup-base.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/rup-theme.min.css" rel="stylesheet" type="text/css" />


