<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- jQuery 1.7.2-->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.7.2.js" type="text/javascript"></script>

<!-- RUP-CORE -->
<script src="${staticsUrl}/rup/scripts/rup.utils-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.base-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.compatibility-2.0.0.js" type="text/javascript"></script>

<!-- jQuery UI 1.8.20-->
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui-1.8.20.custom.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.multidatespicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.timepicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.autocomplete.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.selectmenu.js" type="text/javascript"></script><!-- combo -->

<!-- jqGrid 4.3.2 -->
<script src="${staticsUrl}/rup/scripts/core/jqGrid/jqGrid-4.3.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jqGrid/jquery.jqGrid.fluid.js" type="text/javascript"></script>

<!-- Utilidades adicionales -->
<script src="${staticsUrl}/rup/scripts/core/utils/form2object.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.blockUI.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.fileupload.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.fileupload-ui.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.form.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.iframe-transport.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.json-2.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.numeric.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.qtip.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.url.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.validate.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.xdr-transport.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/xbreadcrumbs.js" type="text/javascript"></script>

<!-- Patrones RUP -->
<script src="${staticsUrl}/rup/scripts/rup.accordion-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.autocomplete-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.breadCrumb-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.combo-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.date-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.dialog-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.feedback-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.form-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.grid-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.lang-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.maint-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.menu-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.message-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tabs-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.time-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.toolbar-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tooltip-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.upload-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.validate-2.0.0.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.wizard-2.0.0.js" type="text/javascript"></script>

<!-- Ajustes de compatibilidad de menú -->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.7.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.core.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.widget.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.position.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.menu.js" type="text/javascript"></script>
<script type="text/javascript"> widgetMenu = $.noConflict(true); </script> 