<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- BASE (sub-productos para patrones) -->
<link href="${staticsUrl}/rup/basic-theme/ui.jqgrid.css" rel="stylesheet" type="text/css" />

<!-- jQuery UI (custom-theme) -->
<link href="${staticsUrl}/rup/custom-theme/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css" />

<!-- Patrones (basic-theme) -->
<link href="${staticsUrl}/rup/basic-theme/theme.rup.base-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.autocomplete-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.breadCrumb-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.combo-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.date-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.feedback-1.1.0.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.grid-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.lang-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.maint-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.menu-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.messages-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tabs-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.time-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.toolbar-1.1.1.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/basic-theme/theme.rup.tooltip-1.1.1.css" rel="stylesheet" type="text/css" />
	