 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<link href="${staticsUrl}/rup/portal/externals/bootstrap/bt4.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/font-awesome/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/rup-base.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/rup-theme.css" rel="stylesheet" type="text/css" />



