<%--  
 -- Copyright 2015 E.J.I.E., S.A.
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 -- 
 -- http://ec.europa.eu/idabc/eupl.html
 -- 
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito,
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia. 
 --%>
 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!--[if !(IE)]> -->
<link href="${staticsUrl}/rup/css/rup.min.css" rel="stylesheet" type="text/css" />
<!--<![endif]-->
<!--[if IE]>
<link href="${staticsUrl}/rup/css/jquery-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/gridstack.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/gridstack-extra.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/jquery.fileupload.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/css/rup.css" rel="stylesheet" type="text/css" />
<![endif]-->


