 
<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<link href="${staticsUrl}/rup/portal/externals/bt4.min.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/font-awesome.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/rup-base.css" rel="stylesheet" type="text/css" />
<link href="${staticsUrl}/rup/portal/rup-theme.css" rel="stylesheet" type="text/css" />



