<%@page pageEncoding="UTF-8" contentType="text/html; charset=UTF-8"%>

<!-- jQuery 1.8.0-->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.8.0.js" type="text/javascript"></script>

<!-- RUP-CORE -->
<script src="${staticsUrl}/rup/scripts/rup.utils-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.base-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.compatibility-2.4.1.js" type="text/javascript"></script>

<!-- jQuery UI 1.8.23-->
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui-1.8.23.custom.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.multidatespicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery-ui.timepicker.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.autocomplete.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.ui.selectmenu.js" type="text/javascript"></script><!-- combo -->
<script src="${staticsUrl}/rup/scripts/core/ui/jquery.multiselect.js" type="text/javascript"></script><!-- multicombo -->

<!-- jqGrid 4.4.1 -->
<script src="${staticsUrl}/rup/scripts/core/jqGrid/jquery.jqGrid.src.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jqGrid/jqGrid.rup.table.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/jqGrid/jqGrid.fluid.js" type="text/javascript"></script>

<!-- Utilidades adicionales -->
<script src="${staticsUrl}/rup/scripts/core/utils/form2object.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.blockUI.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.fileDownload.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.fileupload.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.fileupload-ui.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.form.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.iframe-transport.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.json-2.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.numeric.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.qtip.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.url.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.validate.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.xdr-transport.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/xbreadcrumbs.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.jstree.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.hotkeys.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/utils/jquery.contextMenu.js" type="text/javascript"></script>

<!-- Patrones RUP -->
<script src="${staticsUrl}/rup/scripts/rup.accordion-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.autocomplete-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.breadCrumb-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.combo-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.contextMenu-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.date-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.dav-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.dialog-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.feedback-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.form-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.grid-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.grid.jerarquia-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.lang-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.maint-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.menu-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.message-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.report-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.core-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.contextMenu-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.filter-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.search-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.toolbar-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.feedback-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.fluid-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.formEdit-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.inlineEdit-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.multiselection-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.jerarquia-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.masterDetail-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup_table/rup.table.report-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tabs-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.time-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.toolbar-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tooltip-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.upload-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.validate-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.wizard-2.4.1.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/rup.tree-2.4.1.js" type="text/javascript"></script>

<!-- Ajustes de compatibilidad de menú -->
<script src="${staticsUrl}/rup/scripts/core/jquery-1.7.2.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.core.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.widget.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.position.menu.js" type="text/javascript"></script>
<script src="${staticsUrl}/rup/scripts/core/ui/menu/jquery.ui.menu.js" type="text/javascript"></script>
<script type="text/javascript"> widgetMenu = $.noConflict(true); </script> 