/**
${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by UDA", 0)}, ${date}.
 * @author UDA
 */
 
<#assign camposDoc = ctrlUtils.getPrimaryKey(pojo,cfg)>
<#assign primariaSizes = camposDoc.size()>
	<#if primariaSizes == 1>
		<#list camposDoc as camposPrim>
          <#if camposPrim[0].equals('id') >	 
			<#assign textHdiv = ', ${pojo.importType("org.hdiv.services.SecureIdentifiable")}<${pojo.importType(camposPrim[1])}>' >
		  <#else>
		  	<#assign textHdiv = ', ${pojo.importType("org.hdiv.services.SecureIdContainer")}' >
		  </#if>	
		</#list> 
	<#else>	
		<#assign textHdiv = ', ${pojo.importType("org.hdiv.services.SecureIdentifiable")}<String>' >
	</#if>
<#include "../ejb3TypeDeclaration.ftl"/>
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}${textHdiv}