package ${packageNameRemoting};
import javax.ejb.Remote;
<#if isEjb3>
	import ${namePackageService}.${serviceName} ;
<#else>
  	<#--import ${namePackageEjb}.${serviceName} ;-->
	<#foreach parametro in skeletonUtils.generateParameterImports(methods,false)>	
		import ${stubUtils.replaceDto(parametro)};
	</#foreach>
</#if>
/**
* "${serviceName}StubRemote generated by UDA 1.0".
* @author UDA
 */

@Remote
<#if isEjb3>
public interface ${serviceName}StubRemote extends ${serviceName}{
<#else>
public interface ${serviceName}StubRemote{ 
	<#assign listaMetodos = methods>
	<#list methods as metodo>
	    <#assign param = metodo[3]>
		public <#if isJpa><#foreach parametro in skeletonUtils.getParametersSkeleton(metodo[1]+';',false,false)>${parametro}</#foreach><#else>${metodo[2]}</#if> ${metodo[0]} (<#list skeletonUtils.getParametersSkeleton(param,false,false) as parametro>${parametro} ${ctrUtils.stringDecapitalize(parametro)}Var<#if parametro_has_next>,</#if></#list> )throws Exception;
	</#list>	
</#if>


}