/**
* ${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by UDA 1.0", 0)}, ${date}.
* @author UDA
 */
<#include "Ejb3TypeDeclaration.ftl"/>

${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} extends  ${pojo.getDeclarationName()}Dto ${pojo.getImplementsDeclaration()}