/**
* ${pojo.getClassJavaDoc(pojo.getDeclarationName() + " generated by UDA 1.0", 0)}, ${date}.
* @author UDA
 */

${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()}Dto ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}