/**
${pojo.getClassJavaDoc(render.eval(ctx, pojo.getDeclarationName() + " generated by UDA 1.0"), 0)}
 */
${templates.Ejb3TypeDeclaration}
${pojo.getClassModifiers()} ${pojo.getDeclarationType()} ${pojo.getDeclarationName()} ${pojo.getExtendsDeclaration()} ${pojo.getImplementsDeclaration()}