<#-- 
 -- Copyright 2011 E.J.I.E., S.A.
 --
 -- Licencia con arreglo a la EUPL, Versión 1.1 exclusivamente (la «Licencia»);
 -- Solo podrá usarse esta obra si se respeta la Licencia.
 -- Puede obtenerse una copia de la Licencia en
 --
 --      http://ec.europa.eu/idabc/eupl.html
 --
 -- Salvo cuando lo exija la legislación aplicable o se acuerde por escrito, 
 -- el programa distribuido con arreglo a la Licencia se distribuye «TAL CUAL»,
 -- SIN GARANTÍAS NI CONDICIONES DE NINGÚN TIPO, ni expresas ni implícitas.
 -- Véase la Licencia en el idioma concreto que rige los permisos y limitaciones
 -- que establece la Licencia.
 -->
package ${packageNameSkeleton};
import javax.ejb.Remote;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.ejb.TransactionManagement;
import javax.ejb.TransactionManagementType;
import javax.interceptor.Interceptors;
import com.ejie.x38.remote.TransactionMetadata;
import com.ejie.x38.remote.TransactionMetadataSkeletonInterceptor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ejb.interceptor.SpringBeanAutowiringInterceptor;
import ${packageName}.${serviceName};
<#foreach parametro in skeletonUtils.generateParameterImports(methods,isJpa)>	
import ${parametro};
</#foreach>

/**
 * ${serviceName} + "Skeleton generated by UDA".
 * @author UDA
 */

@Stateless(mappedName = "${jndiName}")
@TransactionManagement(TransactionManagementType.CONTAINER)
@Interceptors({SpringBeanAutowiringInterceptor.class, TransactionMetadataSkeletonInterceptor.class})
@Remote(${serviceName}SkeletonRemote.class)
@TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
@SuppressWarnings("rawtypes")
public class ${serviceName}Skeleton implements ${serviceName}SkeletonRemote   {
    @Autowired
	private ${serviceName} ${serviceName?uncap_first};
    <#assign param ="">
	<#assign listaMetodos = methods>
	<#list methods as metodo>
	    <#assign param = metodo[3]>
	    
	/**
	 * Method ${metodo[0]}.
	 *
<#foreach parametro in skeletonUtils.getParametersSkeleton(param,false,isJpa)>
	 * @param arg${parametro_index} ${parametro} 
</#foreach>
	 * @param transactionMetadata TransactionMetadata
<#if metodo[1]!= "void"> 
	 * @return ${metodo[1]}
</#if>
	 */
	@Override
	${skeletonUtils.generateTransactionAttribute(metodo[0])}
	<#--public <#if isJpa><#foreach parametro in skeletonUtils.getParametersSkeleton(metodo[1]+';',false,isJpa)>${stubUtils.replaceDto(parametro)}</#foreach><#else>${metodo[2]}</#if> ${metodo[0]} (<#foreach parametro in skeletonUtils.getParametersSkeleton(param,false,isJpa)>${parametro} ${parametro?uncap_first},</#foreach> TransactionMetadata transactionMetadata){-->
	public ${metodo[2]} ${metodo[0]} (<#foreach parametro in skeletonUtils.getParametersSkeleton(param,false,isJpa)>${parametro} arg${parametro_index}, </#foreach>TransactionMetadata transactionMetadata)<#if metodo[4]!= ""> throws ${metodo[4]}</#if> {
	<#if isJpa>
		<#foreach parametro in skeletonUtils.getParametersSkeleton(metodo[1]+';',false,isJpa)><#if parametro!='void'>return</#if></#foreach> this.${serviceName?uncap_first}.${metodo[0]}(<#list skeletonUtils.getParametersSkeleton(param,false,isJpa) as parametro><#if parametro!='Pagination' && parametro!='ArrayList' && parametro!='List'>new ${stubUtils.replaceDto(parametro)}(arg${parametro_index})<#else>arg${parametro_index}</#if><#if parametro_has_next>,</#if></#list>);
	<#else>	
		<#foreach parametro in skeletonUtils.getParametersSkeleton(metodo[1]+';',false,false)><#if parametro!='void'>return</#if></#foreach> this.${serviceName?uncap_first}.${metodo[0]}(<#list skeletonUtils.getParametersSkeleton(param,false,isJpa) as parametro>arg${parametro_index}<#if parametro_has_next>,</#if></#list>);
	</#if>
	}
	</#list>
	
	/**
	 * Method 'get${serviceName}'.
	 *
	 * @return ${serviceName}
	 */
	protected ${serviceName} get${serviceName}() {
		return this.${serviceName?uncap_first};
	}

	/**
	 * Method 'set${serviceName}'.
	 *
	 * @param ${serviceName?uncap_first} ${serviceName}
	 */
	public void set${serviceName}(${serviceName} ${serviceName?uncap_first}) {
		this.${serviceName?uncap_first} = ${serviceName?uncap_first};
	}

}	